### ISSUE TITLE
get luminance doesn't always return the correct number

### ISSUE THREAD

**Issue by FischLu** [waydabber/m1ddc#19]
Hi, I am using two display for MacStudio, one is LG 27UP850 (display 1), another one is LG 27UP650. I am trying to combine Hammerspoon and m1ddc together. I want to know the current brightness before I change it, however, the command
```
m1ddc display 1 get luminance
```
doesn't always return the current brightness (which is 50 during my test), sometimes it returns 0 and I see one time it returns a negative number, as you can see from the image

<img width="412" alt="image" src="https://user-images.githubusercontent.com/10261662/202914063-df18f4fb-a1e8-4c85-a311-0225f08625b1.png">

For `get volume` I have the same problem too..

**Comment by waydabber** [comment]
well, you should make an iteration in your luascript to get the value 5 times and use the max you get. DDC reading is inherently finicky.

**Comment by FischLu** [comment]
thanks, at least I have a solution now.
