### ISSUE TITLE
Support DDC control via HDMI port of Apple Silicon Macs

### ISSUE THREAD

**Issue by StanislavMayorov** [waydabber/m1ddc#28]
Hello! Many thanks for DDC control via HDMI in BetterDisplay. It works great. Could you add this feature in m1ddc please?

**Comment by waydabber** [comment]
I don't think this will be added. Supporting the HDMI port for M1 macs requries a bit more complex code and all that is written in Swift and not open-sourced currently.

**Comment by waydabber** [comment]
But don't despair, I plan to add CLI integration to BetterDisplay to reach the functionality via the Terminal as well!

**Comment by StanislavMayorov** [comment]
BetterDisplay has a lot of features. It will be a great alternative!
