### ISSUE TITLE
Request: add turn off display or other monitor power options

### ISSUE THREAD

**Issue by urosch** [waydabber/m1ddc#30]
hi!
Before going to Apple Silicon M2 Mac mini, I was using ddcctl which had extra option to edit monitor power options: turn off, sleep,...

I guess I'd like to know if that is also possible to implement in m1ddc?
Thank you for your work, I really appreciate what you've done.

**Comment by urosch** [comment]
After looking through code, I found standby argument...
Long story short: `m1ddc set standby 5` turns off the monitor.

have a nice day!

**Comment by waydabber** [comment]
Right, you were faster figuring this out then me giving the answer. :)
