### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [waydabber/m1ddc#40]
👋 it might be good to mark 1.1.0 as latest release, thanks! 🙏 

![image](https://github.com/waydabber/m1ddc/assets/1580956/85959151-758b-44f3-b30b-76a6dd085c11)

relates to https://github.com/Homebrew/homebrew-core/pull/152950

**Comment by waydabber** [comment]
Indeed, sorry, forgot to have that checkbox selected. :)

**Comment by chenrui333** [comment]
thank you! :)
