### ISSUE TITLE
macMini m2 HDMI different address

### ISSUE THREAD

**Issue by scr34m** [waydabber/m1ddc#46]
My DELL U2715H is connected over HDMI and i had to change the address 0x37 to 0xB7, with this tweak is now able to read data.

**Comment by waydabber** [comment]
Hi there - this affects only m1 and entry level m2 Macs, not a HDMI specific issue but related to the HDMI converter chip found in these specific models. BetterDisplay has this built-in, you can use BetterDisplay's CLI to use DDC control. Newer Macs (M2 Pro, M3) do not have this issue and likely future Macs won't either.
